image: python:latest

build:
  script:
    - cd multi-user
    - rm -rf cache tests .git .gitignore .gitmodules docs
    # run the command here 
    - cd multi-user/libs/replication
    - rm -rf tests .git .gitignore
    
  artifacts:
    paths:
      - multi-user

