image: python:latest

build:
  script:
    - git submodules init
    - git submodules update
    - cd multi_user/libs/replication
    - rm -rf tests .git .gitignore
    - cd ../../
    - ls
  artifacts:
    paths:
      - multi_user

