image: python:latest


before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
    - python setup.py test
    - pip install tox flake8  # you can also use tox
    - tox -e py36,flake8

run:
  script:
    - cd multi-user
    - rm -rf cache tests .git .gitignore .gitmodules docs
    # run the command here 
    - cd multi-user/libs/replication
    - rm -rf tests .git .gitignore
    
  artifacts:
    paths:
      - multi-user

