build:
  stage: build
  image: debian:stable-slim
  script:
    - rm -rf tests .git .gitignore script
  artifacts:
    name: multi_user
    paths: 
     - multi_user
  only:
    refs:
        - master
        - develop
        - 132-fix-undo-edit-last-operation-redo-handling-2