test:
  stage: test
  image: debian
  script:
    - apt update 
    - apt upgrade -f -y
    - apt install -f -y python3.7 python3-pip python3.7-dev git blender
    - git submodule init
    - git submodule update
    - python3 -m pip install blender-addon-tester
    - python3 scripts/test_addon.py

