test:
  stage: test
  image: python:latest
  script:
    - git submodule init
    - git submodule update
    - apt update
    # install blender to get all required dependencies
    # TODO: indtall only dependencies
    - apt install -f -y gcc python-dev python3.7-dev
    - apt install -f -y blender
    - python3 -m pip install psutil
    - python3 -m pip install blender-addon-tester
    - python3 scripts/test_addon.py

