image: debian:latest

pytest:
  stage: test
  script:
    - apt-get update -y
    - apt-get install -y python3 python3-pip python3-venv
    - python3 -m venv venv
    - ls venv/bin
    - ls .
    - ./venv/bin/python -m pip install -r requirements.txt
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:  
      junit: report.xml