test:
  image: ubuntu:latest
  script:
    - apt update
    - apt install python git
    - git submodule init
    - git submodule update
    - pip install blender-addon-tester
    - python scripts/test_addon.py multi_user $BLENDER_VERSIONS

