test:
  image: python:latest
  script:
    - git submodule init
    - git submodule update
    - python --version
    - python -m pip install --upgrade pip
    - apt update
    - apt install -f -y blender
    - pip install blender-addon-tester
    - cd scripts
    - python test_addon.py multi_user 2.82

