test:
  stage: test
  image: python:3.7
  script:
    - git submodule init
    - git submodule update
    - apt-get update && apt-get install -y python3.7-dev 
    # install blender to get all required dependencies
    # TODO: indtall only dependencies
    - apt install -f -y blender  
    - python -m pip install blender-addon-tester
    - python scripts/test_addon.py


