test:
  image: ubuntu:latest
  script:
    - apt update
    - apt install -y python3 python3-pip git
    - git submodule init
    - git submodule update
    - python3 -m pip install blender-addon-tester
    - python3 scripts/test_addon.py multi_user $BLENDER_VERSIONS

